In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

74.94079995155334


In [5]:
x, y = mnist["data"], mnist["target"]

In [6]:
y = y.astype(np.uint8)

In [7]:
x_train, x_test = x[:60000], x[60000:70000]
y_train, y_test = y[:60000], y[60000:70000]

print("x_train shape : ", x_train.shape)
print("x_test shape  : ", x_test.shape)
print("y_train shape : ", y_train.shape)
print("y_test shape  : ", y_test.shape)

x_train shape :  (60000, 784)
x_test shape  :  (10000, 784)
y_train shape :  (60000,)
y_test shape  :  (10000,)


In [8]:
algorithm_execution_time1 = time()

from sklearn.ensemble import AdaBoostClassifier

adb = AdaBoostClassifier()
adb_model = adb.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [9]:
y_pred = adb.predict(x_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 883    0   25    3    4   28   23    3    3    8]
 [   0 1070    3    8    3    1    4   25   21    0]
 [  30   35  596   32   18    8  208   25   75    5]
 [  28   32   19  678    2   92   30   33   74   22]
 [   4    2   17   14  708   16   10   80   35   96]
 [  29   32    6  122   27  526   22   19   71   38]
 [  20   10   35    6   26   32  822    1    6    0]
 [   7   16   23    8   14    7    1  804   20  128]
 [  40   48   11   91   15   34   22   18  661   34]
 [   9   11   23   32  161   18    1  169   34  551]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       980
           1       0.85      0.94      0.90      1135
           2       0.79      0.58      0.67      1032
           3       0.68      0.67      0.68      1010
           4       0.72      0.72      0.72       982
           5       0.69      0.59      0.64       892
           6       0.72      0.86      0.78       958
           7       0.68      0.78   

In [11]:
print(algorithm_execution_time2)

83.18863034248352
