In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

77.86625337600708


In [5]:
x, y = mnist["data"], mnist["target"]

In [6]:
y = y.astype(np.uint8)

In [7]:
x_train, x_test = x[:60000], x[60000:70000]
y_train, y_test = y[:60000], y[60000:70000]

print("x_train shape : ", x_train.shape)
print("x_test shape  : ", x_test.shape)
print("y_train shape : ", y_train.shape)
print("y_test shape  : ", y_test.shape)

x_train shape :  (60000, 784)
x_test shape  :  (10000, 784)
y_train shape :  (60000,)
y_test shape  :  (10000,)


In [8]:
algorithm_execution_time1 = time()

from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [9]:
y_pred = classifier.predict(x_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 918    1   10    7    5   13    9    4    9    4]
 [   1 1096    8    3    2    7    6    3    8    1]
 [   8    9  891   26   16   13    8   30   23    8]
 [   6    8   28  873    9   36    5    8   17   20]
 [   5    3    9    5  861    4   13   14   26   42]
 [  10    5    6   43    8  749   24    4   27   16]
 [  17    3   14   10   18   18  848    1   24    5]
 [   2   10   31   15    6   10    1  922    9   22]
 [   7    9   33   39   22   25   11   11  783   34]
 [  13    5    7   17   38   15    6   19   20  869]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       980
           1       0.95      0.97      0.96      1135
           2       0.86      0.86      0.86      1032
           3       0.84      0.86      0.85      1010
           4       0.87      0.88      0.88       982
           5       0.84      0.84      0.84       892
           6       0.91      0.89      0.90       958
           7       0.91      0.90   

In [11]:
print(algorithm_execution_time2)

35.89382743835449
