In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

40.035566091537476


In [5]:
x, y = mnist["data"], mnist["target"]

In [6]:
y = y.astype(np.uint8)

In [7]:
x_train, x_test = x[:60000], x[60000:70000]
y_train, y_test = y[:60000], y[60000:70000]

In [8]:
print("x_train shape : ", x_train.shape)
print("x_test shape  : ", x_test.shape)
print("y_train shape : ", y_train.shape)
print("y_test shape  : ", y_test.shape)

x_train shape :  (60000, 784)
x_test shape  :  (10000, 784)
y_train shape :  (60000,)
y_test shape  :  (10000,)


In [9]:
algorithm_execution_time1 = time()

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [10]:
y_pred = lr.predict(x_test)

y_pred_rounded = np.round(y_pred)

y_pred_int = y_pred_rounded.astype(int)

y_pred_int = np.where(y_pred < 0, 0, y_pred_int)
y_pred_int = np.where(y_pred > 9, 9, y_pred_int)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_int))
print(classification_report(y_test, y_pred_int))

[[228 323 258 104  35  22   8   2   0   0]
 [  1 238 559 224  89  16   7   1   0   0]
 [ 35 124 236 305 224  84  20   1   3   0]
 [  8  43 196 326 270 102  41  12   9   3]
 [  0   0   6  36 198 338 249 115  37   3]
 [  0   3  21 118 252 291 143  34  19  11]
 [  3   4  23  73 152 269 269 118  45   2]
 [  0   1   7  25  73 144 244 284 153  97]
 [  0   1  10  26  99 189 281 227 103  38]
 [  0   1   5   8  25  59 144 313 319 135]]
              precision    recall  f1-score   support

           0       0.83      0.23      0.36       980
           1       0.32      0.21      0.25      1135
           2       0.18      0.23      0.20      1032
           3       0.26      0.32      0.29      1010
           4       0.14      0.20      0.17       982
           5       0.19      0.33      0.24       892
           6       0.19      0.28      0.23       958
           7       0.26      0.28      0.27      1028
           8       0.15      0.11      0.12       974
           9       0.47     

In [13]:
print(algorithm_execution_time2)

4.117211818695068
