In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

51.67497968673706


In [5]:
x, y = mnist.data, mnist.target

In [6]:
y = y.astype(np.uint8)

In [7]:
x_train, x_test = x[:60000], x[60000:70000]
y_train, y_test = y[:60000], y[60000:70000]

In [9]:
algorithm_execution_time1 = time()

from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(activation = 'relu', max_iter = 2000, hidden_layer_sizes = (16, 16,))
clf.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [11]:
y_pred = clf.predict(x_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 963    0    3    0    1    2    4    4    3    0]
 [   0 1114    2    7    0    1    2    1    8    0]
 [  16    5  947   17   10    1    5   12   19    0]
 [   2    0   36  931    0   18    0    9    8    6]
 [   0    2   10    1  918    1   14    6    2   28]
 [   4    0    1   33    1  803   16    3   18   13]
 [   9    5    8    1    3    6  922    0    4    0]
 [   2    5   16   12    2    0    0  953    3   35]
 [   8    4    7   21    8   14   15    7  880   10]
 [   3    6    3   13   25    4    2    9    9  935]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.98      0.98      0.98      1135
           2       0.92      0.92      0.92      1032
           3       0.90      0.92      0.91      1010
           4       0.95      0.93      0.94       982
           5       0.94      0.90      0.92       892
           6       0.94      0.96      0.95       958
           7       0.95      0.93   

In [14]:
print(algorithm_execution_time2)

723.1296730041504
