In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

43.88542342185974


In [5]:
x, y = mnist.data, mnist.target
y = y.astype(np.uint8)

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_x = scaler.fit_transform(x)

In [7]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 70)
pca_x = pca.fit_transform(scaled_x)

In [8]:
x_train, x_test = pca_x[:60000], pca_x[60000:]
y_train, y_test = y[:60000], y[60000:]

In [9]:
algorithm_execution_time1 = time()

from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [11]:
y_predict = svm_model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[ 970    0    1    1    0    3    3    1    1    0]
 [   0 1128    3    0    0    1    1    0    1    1]
 [   4    0 1006    2    1    0    1   10    6    2]
 [   0    0    0  986    1    5    0    9    8    1]
 [   0    1    6    0  948    0    6    6    3   12]
 [   2    0    1   13    1  861    5    3    5    1]
 [   4    3    1    1    3    8  934    1    3    0]
 [   2    9   12    1    3    0    0  986    2   13]
 [   3    0    4    7    5    8    1    6  936    4]
 [   2    5    2    7   15    3    0   11    7  957]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.98      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.97      0.98      0.97      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.97      0.97       892
           6       0.98      0.97      0.98       958
           7       0.95      0.96   

In [13]:
print(algorithm_execution_time2)

92.91316294670105
