In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

89.72405171394348


In [5]:
x, y = mnist.data, mnist.target

In [6]:
y = y.astype(np.uint8)

In [7]:
#splitting target 

y_train, y_test = y[:60000], y[60000:] 

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_x = scaler.fit_transform(x)

In [9]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 70)
pca_x = pca.fit_transform(scaled_x)

In [10]:
#splitting of data after scaling and pca

x_train, x_test = pca_x[:60000], pca_x[60000:] 

In [11]:
algorithm_execution_time1 = time()

from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier()
clf = classifier.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [12]:
y_pred = classifier.predict(x_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 875    0   15    6    9   26   18   13   10    8]
 [   2 1099    7    5    2    2    3    4   10    1]
 [  16    6  846   47   18    8   23   16   50    2]
 [   6    7   33  810    2   48    8   11   64   21]
 [   4    5   21    6  809   14   15   20   19   69]
 [  21    3   12   51   14  687   13   12   57   22]
 [  24    2   30    1   11   19  855    1   12    3]
 [   3   10   20   17   15    4    1  859   21   78]
 [  10    6   28   51   28   49   15   14  747   26]
 [  10    5   12   19   59   13    2   65   23  801]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.90       980
           1       0.96      0.97      0.96      1135
           2       0.83      0.82      0.82      1032
           3       0.80      0.80      0.80      1010
           4       0.84      0.82      0.83       982
           5       0.79      0.77      0.78       892
           6       0.90      0.89      0.89       958
           7       0.85      0.84   

In [14]:
print(algorithm_execution_time2)

21.525676488876343
