In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

44.30584645271301


In [5]:
x, y = mnist["data"], mnist["target"]

In [6]:
y = y.astype(np.uint8)

In [7]:
x_train, x_test = x[:60000], x[60000:70000]
y_train, y_test = y[:60000], y[60000:70000]

print("x_train shape : ", x_train.shape)
print("x_test shape  : ", x_test.shape)
print("y_train shape : ", y_train.shape)
print("y_test shape  : ", y_test.shape)

x_train shape :  (60000, 784)
x_test shape  :  (10000, 784)
y_train shape :  (60000,)
y_test shape  :  (10000,)


In [8]:
algorithm_execution_time1 = time()

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [9]:
y_pred = rf.predict(x_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 968    0    0    0    0    3    4    1    3    1]
 [   0 1124    1    3    0    2    3    0    1    1]
 [   5    1  998    6    3    1    2    9    7    0]
 [   0    0    7  974    0    8    0    8    9    4]
 [   1    0    1    0  955    0    5    0    2   18]
 [   4    0    1   11    3  860    3    1    6    3]
 [   7    3    1    0    3    5  936    0    3    0]
 [   2    4   21    3    1    0    0  986    2    9]
 [   4    0    5    8    7    5    4    5  926   10]
 [   9    5    2   15   13    2    1    4    3  955]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.97      0.96      1032
           3       0.95      0.96      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.96   

In [11]:
print(algorithm_execution_time2)

49.01059651374817
