In [1]:
from time import time
initial_time = time()

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version = 1)

In [4]:
data_load_time = time() - initial_time
print(data_load_time)

44.63833951950073


In [5]:
x, y = mnist.data, mnist.target

In [6]:
y = y.astype(np.uint8)

In [7]:
x_train, x_test = x[:60000], x[60000:70000]
y_train, y_test = y[:60000], y[60000:70000]

In [8]:
algorithm_execution_time1 = time()

from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier

svc_model = SVC()
bagging_model = BaggingClassifier(base_estimator = svc_model, n_estimators=10, max_samples = 0.8, bootstrap=True, random_state = 42)
bagging_model.fit(x_train, y_train)

algorithm_execution_time2 = time() - algorithm_execution_time1

In [9]:
y_predict = bagging_model.predict(x_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[ 973    0    1    0    0    2    1    1    2    0]
 [   0 1126    3    1    0    1    1    1    2    0]
 [   5    1 1009    2    1    0    1    7    5    1]
 [   0    0    3  992    0    3    0    6    5    1]
 [   0    0    5    0  963    0    3    0    1   10]
 [   2    0    0   11    1  870    4    0    2    2]
 [   7    2    1    0    2    4  941    0    1    0]
 [   1    6   12    2    1    0    0  997    0    9]
 [   4    0    1    6    5    3    2    3  947    3]
 [   4    4    1    7   12    1    1    8    4  967]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.98      1032
           3       0.97      0.98      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.98      0.98       892
           6       0.99      0.98      0.98       958
           7       0.97      0.97   

In [11]:
print(algorithm_execution_time2)

964.7697553634644
